version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ""

  elixir:
    build: .
    image: elixir
    links:
      - db
