- command: dokku plugin:list
  name: list dokku plugins
  register: dokku_plugin_result
  changed_when: false
- command: dokku plugin:install https://github.com/dokku/dokku-letsencrypt.git
  name: install letsencrypt dokku plugin
  register: dokku_plugin_install_letsencrypt_result
  become: true
  when: "'letsencrypt' not in dokku_plugin_result.stdout"
  changed_when: dokku_plugin_install_letsencrypt_result is succeeded
- include_role:
    name: dokku/config
  vars:
    value: DOKKU_LETSENCRYPT_EMAIL={{letsencrypt_email}}
    scope: global
- command: crontab -l -u dokku
  name: list crontab entries
  register: crontab_list_result
  become: true
  changed_when: false
  failed_when: crontab_list_result.rc != 0 and (crontab_list_result.rc != 1 or crontab_list_result.stderr != "no crontab for dokku")
- command: dokku letsencrypt:cron-job --add
  name: add dokku letsencrypt cron job
  become: true
  register: dokku_letsencrypt_add_cron_job_result
  when: "'@daily /var/lib/dokku/plugins/available/letsencrypt/cron-job' not in crontab_list_result.stdout_lines"
  changed_when: dokku_letsencrypt_add_cron_job_result is succeeded
